import sys
import random

def printHangman(numGuesses):
   if numGuesses == 10:
      print("\n\n")
      print("     ---------------")
      print("     |              |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("           -----------------\n\n")
   elif numGuesses == 9:
      print("\n\n")
      print("     ---------------")
      print("     |              |")
      print("    ***             |")
      print("   *   *            |")
      print("    ***             |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("           -----------------\n\n")
   elif numGuesses == 8:
      print("\n\n")
      print("        -------------")
      print("        |           |")
      print("      *****         |")
      print("      *****         |")
      print("     *******        |")
      print("      *   *         |")
      print("       ***          |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("           -----------------\n\n")
   elif numGuesses == 7:
      print("\n\n")
      print("        -------------")
      print("        |           |")
      print("      *****         |")
      print("      *****         |")
      print("     *******        |")
      print("      *   *         |")
      print("       ***          |")
      print("        *           |")
      print("        *           |")
      print("        *           |")
      print("        *           |")
      print("        *           |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("           -----------------\n\n")
   elif numGuesses == 6:
      print("\n\n")
      print("        -------------")
      print("        |           |")
      print("      *****         |")
      print("      *****         |")
      print("     *******        |")
      print("      *   *         |")
      print("       ***          |")
      print("        *           |")
      print("        *           |")
      print("        *           |")
      print("        *           |")
      print("        *           |")
      print("       *            |")
      print("      *             |")
      print("     *              |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("           -----------------\n\n")
   elif numGuesses == 5:
      print("\n\n")
      print("        -------------")
      print("        |           |")
      print("      *****         |")
      print("      *****         |")
      print("     *******        |")
      print("      *   *         |")
      print("       ***          |")
      print("        *           |")
      print("        *           |")
      print("        *           |")
      print("        *           |")
      print("        *           |")
      print("       * *          |")
      print("      *   *         |")
      print("     *     *        |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("           -----------------\n\n")
   elif numGuesses == 4:
      print("\n\n")
      print("        -------------")
      print("        |           |")
      print("      *****         |")
      print("      *****         |")
      print("     *******        |")
      print("      *   *         |")
      print("       ***          |")
      print("    *   *           |")
      print("     *  *           |")
      print("      * *           |")
      print("        *           |")
      print("        *           |")
      print("       * *          |")
      print("      *   *         |")
      print("     *     *        |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("           -----------------\n\n")
   elif numGuesses == 3:
      print("\n\n")
      print("        -------------")
      print("        |           |")
      print("      *****         |")
      print("      *****         |")
      print("     *******        |")
      print("      *   *         |")
      print("       ***          |")
      print("    *   *   *       |")
      print("     *  *  *        |")
      print("      * * *         |")
      print("        *           |")
      print("        *           |")
      print("       * *          |")
      print("      *   *         |")
      print("     *     *        |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("                    |")
      print("           -----------------\n\n")


def Hangman():
   
   words = open('/usr/share/dict/words').read().splitlines()
   word = words.pop(random.randint(0,len(words))).lower()
   num_guesses,check,ndx = 10,0,0   
   current = ''.join(['-' for c in range(0,len(word))])
   char_list,guessed_letters = [],[]

   while True:
      ndx = 0
      if check == 0:
         print("\nWelcome to Hangman! Here is your current word:", current)
      else:
         print("Current word:", current)
      
      print("Letters guessed so far:", guessed_letters)
      print("Incorrect guesses remaining:", num_guesses, "\n")
      userInput = input("Enter a letter, or type \'quit\' to exit: ")
      print("")
      if userInput.lower() == 'quit':
         print("Your word was '", word.upper(),"'\nThanks for playing!", sep='')
         sys.exit()
      elif len(userInput) != 1 or not userInput.isalpha():
         print("Please enter a single english letter.\n")
      else: #correct case
         if userInput in guessed_letters:
            print("You already guessed that letter. Try again.")
         elif userInput in word:
            char_list = list(current)
            print("You guessed a correct letter!")
            for c in word:
               if c == userInput:
                  char_list[ndx] = c
               ndx += 1
            current = ''.join(char_list)
         else:
            print("That letter is incorrect.")
            num_guesses -= 1
         if userInput not in guessed_letters:
            guessed_letters.append(userInput)
      
      if current == word:
         print("Congratulations! You've guessed the word ('", word.upper(), "')!\nGood job!", sep='')
         sys.exit()

      if num_guesses == 0:
         print("You are out of guesses!")
         print("Your word was '", word.upper(), "'\nThanks for playing!", sep='')
         sys.exit()

      printHangman(num_guesses)

      check += 1
      

if __name__ == '__main__':
   Hangman()
